/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Prompter } from "./components/prompt/stellar-prompt";
export namespace Components {
    interface StellarPrompt {
        "prompter": Prompter;
    }
    interface StellarWalletP2p {
    }
}
declare global {
    interface HTMLStellarPromptElement extends Components.StellarPrompt, HTMLStencilElement {
    }
    var HTMLStellarPromptElement: {
        prototype: HTMLStellarPromptElement;
        new (): HTMLStellarPromptElement;
    };
    interface HTMLStellarWalletP2pElement extends Components.StellarWalletP2p, HTMLStencilElement {
    }
    var HTMLStellarWalletP2pElement: {
        prototype: HTMLStellarWalletP2pElement;
        new (): HTMLStellarWalletP2pElement;
    };
    interface HTMLElementTagNameMap {
        "stellar-prompt": HTMLStellarPromptElement;
        "stellar-wallet-p2p": HTMLStellarWalletP2pElement;
    }
}
declare namespace LocalJSX {
    interface StellarPrompt {
        "prompter"?: Prompter;
    }
    interface StellarWalletP2p {
    }
    interface IntrinsicElements {
        "stellar-prompt": StellarPrompt;
        "stellar-wallet-p2p": StellarWalletP2p;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stellar-prompt": LocalJSX.StellarPrompt & JSXBase.HTMLAttributes<HTMLStellarPromptElement>;
            "stellar-wallet-p2p": LocalJSX.StellarWalletP2p & JSXBase.HTMLAttributes<HTMLStellarWalletP2pElement>;
        }
    }
}
